#!/bin/bash

set -x


if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

#if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_20 ]
#        then
#                cd $OPENSHIFT_DATA_DIR
#                wget http://www.java.net/download/jdk8u20/archive/b17/binaries/jdk-8u20-ea-bin-b17-linux-x64-04_jun_2014.tar.gz
#                tar xvf *.tar.gz
#                rm -f *.tar.gz
#fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.14 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget https://services.gradle.org/distributions/gradle-2.14-bin.zip
                unzip *.zip
                rm -f *.zip
fi


cd $OPENSHIFT_REPO_DIR
export M2=$OPENSHIFT_DATA_DIR/gradle-2.14/bin
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/.gradle
#$export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export JAVA_HOME=/usr/lib/jvm/java-1.8.0
export PATH=$JAVA_HOME/bin:$M2:$PATH

gradle bootRepackage
